# Generated by Django 2.1.7 on 2019-03-02 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the agency', max_length=255)),
                ('shortname', models.CharField(blank=True, help_text='Abbreviation', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the project', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describes the purpose of the project, the main beneficiaries and may include a short text of the proposal')),
                ('total_project_cost', models.FloatField(blank=True, help_text='The Total Project Cost on record', null=True)),
                ('implementation_period', models.DurationField(blank=True, help_text='Duration of the project', null=True)),
                ('implementation_from', models.DateTimeField(blank=True, help_text='Start datetime of implementation', null=True)),
                ('implementation_to', models.DateTimeField(blank=True, help_text='End datetime of implementation', null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ICCCCDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Datetime of ICCDate instance')),
                ('description', models.CharField(help_text='Optional: Short text describing the date', max_length=180)),
                ('project', models.ForeignKey(help_text='Reference to project', on_delete=django.db.models.deletion.CASCADE, related_name='icc_cc_dates', to='govproject.GovernmentProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICCTBDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Datetime of ICCDate instance')),
                ('description', models.CharField(help_text='Optional: Short text describing the date', max_length=180)),
                ('project', models.ForeignKey(help_text='Reference to project', on_delete=django.db.models.deletion.CASCADE, related_name='icc_tb_dates', to='govproject.GovernmentProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=510)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.AddField(
            model_name='governmentproject',
            name='administrative_area',
            field=models.ForeignKey(help_text='Target region of the project', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='govproject.Region'),
        ),
        migrations.AddField(
            model_name='governmentproject',
            name='funding_source',
            field=models.ForeignKey(blank=True, help_text='Source of funding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='govproject.FundingSource'),
        ),
        migrations.AddField(
            model_name='governmentproject',
            name='implementing_agency',
            field=models.ForeignKey(blank=True, help_text='Agency in charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='govproject.Agency'),
        ),
    ]
