# Generated by Django 2.1.7 on 2019-03-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("govproject", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="fundingsource",
            name="name",
            field=models.CharField(
                help_text="Name of the funding source", max_length=255
            ),
        ),
        migrations.RemoveField(
            model_name="governmentproject", name="administrative_area"
        ),
        migrations.AddField(
            model_name="governmentproject",
            name="administrative_area",
            field=models.ManyToManyField(
                help_text="Target region of the project",
                related_name="projects",
                to="govproject.Region",
            ),
        ),
    ]
