# Generated by Django 2.1.7 on 2019-03-19 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("govproject", "0002_auto_20190308_1410"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "when_start",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Defaults to datetime added"
                    ),
                ),
                (
                    "when_end",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Defaults to datetime added"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Describe what the report is about"),
                ),
                (
                    "report_type",
                    models.IntegerField(
                        choices=[
                            (0, "SUPPLEMENTAL"),
                            (1, "BLOCKER"),
                            (2, "DISCONTINUED"),
                        ],
                        default=0,
                        help_text="'Supplemental' are for normal reports. 'Blocker' indicates obstacles in progressing the project. While 'Discontinued' flags a project as incomplete.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        help_text="The author of the report",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="added_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project to which this report is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="govproject.GovernmentProject",
                    ),
                ),
            ],
        )
    ]
