# Generated by Django 2.1.7 on 2019-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0003_progressreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='progressreport',
            name='tags',
            field=models.ManyToManyField(help_text='Optional tags', related_name='tags', to='govproject.Tag'),
        ),
    ]
