# Generated by Django 2.2 on 2019-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0005_governmentproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='when_end',
            field=models.DateTimeField(blank=True, help_text='Defaults to datetime added', null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='when_start',
            field=models.DateTimeField(blank=True, help_text='Defaults to datetime added', null=True),
        ),
    ]
