# Generated by Django 2.2 on 2019-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0007_auto_20190427_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='description',
            field=models.CharField(blank=True, help_text='Short description', max_length=512),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='media',
            field=models.FileField(help_text='Project media file', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
