# Generated by Django 2.2 on 2019-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0009_governmentproject_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentproject',
            name='media_files',
            field=models.ManyToManyField(blank=True, help_text='Attached media files to the project', null=True, related_name='projects', to='govproject.ProjectMedia'),
        ),
    ]
