# Generated by Django 2.2 on 2019-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0010_auto_20190430_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='status',
            field=models.IntegerField(choices=[(0, 'INITIAL'), (1, 'VERIFIED'), (2, 'APPROVED')], default=0, help_text='Verification status of a progress report'),
        ),
    ]
