# Generated by Django 2.2.1 on 2019-05-02 15:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0014_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
