# Generated by Django 2.2.1 on 2019-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govproject', '0015_auto_20190502_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentproject',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentproject',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Mark the project as complete'),
        ),
    ]
